version: "3"

services:
  node-app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env

  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes: 
      - mongo-db:/data/db

volumes: 
  mongo-db:
