version: "3"

services:
  node-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
    # to pass the env variables from the .env file
    # env_file:
    #     - ./.env
